nelmio_api_doc:
    documentation:
        info:
            title: API RESTO
            description: This is an awesome app!
            version: 1.0.0
        components:
            securitySchemes:
                X-Auth-Token:
                    type: apiKey
                    name: X-Auth-Token
                    in: header
        security:
            - X-Auth-Token: []
    areas: # to filter documented areas
        path_patterns:
            - ^/api(?!/doc$) # Accepts routes under /api except /api/doc
